apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../gcr
images:
  - name: k8s.gcr.io/provider-aws/aws-ebs-csi-driver
    newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/aws-ebs-csi-driver
  - name: k8s.gcr.io/sig-storage/csi-provisioner
    newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-provisioner
  - name: k8s.gcr.io/sig-storage/csi-attacher
    newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-attacher
  - name: k8s.gcr.io/sig-storage/livenessprobe
    newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/livenessprobe
  - name: k8s.gcr.io/sig-storage/csi-snapshotter
    newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-snapshotter
  - name: k8s.gcr.io/sig-storage/csi-resizer
    newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-resizer
  - name: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    newName: 961992271922.dkr.ecr.cn-northwest-1.amazonaws.com.cn/eks/csi-node-driver-registrar
